export enum AuthProvider {
  LOCAL = 'LOCAL',
  GOOGLE = 'GOOGLE',
  PHONE = 'PHONE',
}

export enum UserRole {
  PARENT = 'PARENT',
  CAREGIVER = 'CAREGIVER',
  COMMUNITY = 'COMMUNITY',
}

export enum OtpType {
  PHONE_LOGIN = 'PHONE_LOGIN',
  PHONE_VERIFICATION = 'PHONE_VERIFICATION',
  PASSWORD_RESET_PHONE = 'PASSWORD_RESET_PHONE',
  PASSWORD_RESET_EMAIL = 'PASSWORD_RESET_EMAIL',
  PASSWORD_RESET_SESSION = 'PASSWORD_RESET_SESSION',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
}
